steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA', '.'] # <-- MODIFIED

# 2. Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA'] # <-- MODIFIED

# 3. Get GKE credentials
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'my-gke-autopilot-cluster'
  - '--region'
  - 'asia-south1' # <-- MODIFIED

# 4. Update the image in the Kubernetes deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: kubectl
  args:
  - 'set'
  - 'image'
  - 'deployment/python-app-deployment'
  - 'python-app-container=asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA' # <-- MODIFIED

# ... (rest of the file is the same) ...

images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA' # <-- MODIFIED
