steps:
# Step 1: Build the Docker image, tagging it with the short commit SHA
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA', '.']

# Step 2: Push the Docker image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA']

# Step 3: Authenticate with the GKE cluster
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'my-gke-autopilot-cluster'
  - '--region'
  - 'asia-south1'

# Step 4: Update the deployment to use the new Docker image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: kubectl
  args:
  - 'set'
  - 'image'
  - 'deployment/python-app-deployment'
  - 'python-app-container=asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA'

# Step 5: Apply the service manifest to ensure the service is configured
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: kubectl
  args: ['apply', '-f', 'kubernetes/service.yaml']

# This section lists the images that will be built by this pipeline
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-python-app-repo/my-app:$SHORT_SHA'

# Top-level field to specify the Cloud Storage bucket for logs
logsBucket: 'gs://application-deployment-471707-build-logs'
