apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        # The image path now starts with the new region
        image: "asia-south1-docker.pkg.dev/application-deployment-471707/my-python-app-repo/my-app:latest" # <-- MODIFIED
        ports:
        - containerPort: 8080
